version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-template
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node_template
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    ports:
      - $HOST_DATABASE_PORT:5432

  node_template:
    image: node:18.16-alpine
    container_name: node-template
    working_dir: /app
    env_file: ./.env
    volumes:
      - .:/app
    ports:
      - $PORT:$PORT
    depends_on:
      - postgres
    command: sh -c "yarn install ; yarn sequelize db:create ; yarn dev"
